[package]
name = "athena"
version = "0.7.0"
edition = "2021"
rust-version = "1.93.0"

[dependencies]

[features]
encoding_decoding = ["traits"]
compression = ["encoding_decoding"]
checksum = []
byte_bit = []
traits = []
bit_flags = []

[package.metadata.docs.rs]
all-features = true
